-- File generated by the BNF Converter (bnfc 2.9.5).

-- Test for Agda binding of parser.  Requires Agda >= 2.5.4.

module Syntax.Main where
open import Syntax.IOLib
open import Syntax.AST using (printQuery)
open import Syntax.Parser using (Err; parseQuery)

main : IO ⊤
main = do
  file ∷ [] ← getArgs where
    _ → do
      putStrLn "usage: Main <SourceFile>"
      exitFailure
  Err.ok result ← parseQuery <$> readFiniteFile file where
    Err.bad msg → do
      putStrLn "PARSE FAILED\n"
      putStrLn (stringFromList msg)
      exitFailure
  putStrLn "PARSE SUCCESSFUL\n"
  putStrLn (printQuery result)
